#!/bin/bash

set -ue

BRANCH=${1:-master}
ZXBDIST=zxbasic

echo Creating release on branch ${BRANCH}

rm -rf ${ZXBDIST} dist/${ZXBDIST}
git clone --depth=1 --branch ${BRANCH} git@github.com:boriel/zxbasic.git "${ZXBDIST}"

RELEASE=${2:-$(cat $ZXBDIST/zxb/version.py|sed -e 's/^[^0-9]*//'|sed -e 's/[^0-9]*$//')}
echo $RELEASE
echo "VERSION = '$RELEASE'">$ZXBDIST/zxb/version.py

rsync -au $ZXBDIST dist

cd dist/$ZXBDIST

# remove some unneeded files
rm -f *.{ini,spec,yml} setup.py

# copy needed modules (ply, six, ...)
MOD_DIR=../../modules
for f in $(cat ${MOD_DIR}/MANIFEST); do
    cp -va ${MOD_DIR}/$f .
done

./zxbc.py --version
cd ..
rm -rf $ZXBDIST/tests $ZXBDIST/scratch $ZXBDIST/.git $ZXBDIST/*.spec $ZXBDIST/*.egg-info $ZXBDIST/doc $ZXBDIST/docs
find $ZXBDIST -type d -name ".*" -exec rm -rf {} \; 2>/dev/null || true
find $ZXBDIST -type d -name ".*" -delete
find $ZXBDIST -type f -name "*.pyc" -delete
find $ZXBDIST -type d -name "__pycache__" -delete

tar -zcf zxbasic.tar.gz $ZXBDIST
zip -9qr zxbasic.zip $ZXBDIST

mv zxbasic.zip zxbasic-$RELEASE.zip
mv zxbasic.tar.gz zxbasic-$RELEASE.tar.gz

#cd ../$ZXBDIST
#docker run -v "$(pwd):/src/" cdrx/pyinstaller-windows 
#cd ..
#mv $ZXBDIST/dist/windows dist
#cp dist/windows/zxb{asm,pp}/*.exe dist/windows/zxb
#mv dist/zxbasic/{parsetab,library*,examples} dist/windows/zxb
#rm -rf dist/zxbasic
#mv dist/windows/zxb dist/windows/zxbasic

#pushd dist/windows
#zip -9qr zxbasic-$RELEASE-win32.zip zxbasic
#popd
#mv -f dist/windows/zxbasic-$RELEASE-win32.zip dist
#rm -rf dist/windows

cd ..
cp -af win32/* dist/$ZXBDIST
cd dist
rm -f zxbasic-$RELEASE-win32.zip  # Files in zip are not overwritten?
zip -9qr zxbasic-$RELEASE-win32.zip $ZXBDIST
rm -rf $ZXBDIST

echo Uploading...
scp zxbasic-$RELEASE{-win32.zip,.tar.gz,.zip} boriel@boriel.com:/var/www/boriel.com/web/files/zxb
echo Done!
echo Download from:
for i in zxbasic-$RELEASE{-win32.zip,.tar.gz,.zip}; do
    echo http://www.boriel.com/files/zxb/$i
done

