#!/bin/bash

set -ue

BRANCH=${1:-master}
ZXBDIST=zxbasic

echo Creating release on branch $BRANCH

if [[ ! -d "$ZXBDIST" ]]; then
    git clone git@bitbucket.org:zxbasic/zxbasic.git "$ZXBDIST"
fi

cd "$ZXBDIST"
git fetch origin $BRANCH
git checkout $BRANCH
git checkout version.py
git pull origin $BRANCH
cd ..

RELEASE=${2:-$(cat $ZXBDIST/version.py|sed -e 's/^[^0-9]*//'|sed -e 's/[^0-9]*$//')}
echo $RELEASE
echo "VERSION = '$RELEASE'">$ZXBDIST/version.py

rsync -au $ZXBDIST dist

cd dist/$ZXBDIST

# remove some unneeded files
rm -f *.{ini,spec,yml} setup.py

# copy needed modules (ply, six, ...)
MOD_DIR=../../modules
for f in $(cat ${MOD_DIR}/MANIFEST); do
    cp -va ${MOD_DIR}/$f .
done

./zxb.py --version
cd ..
rm -rf $ZXBDIST/tests $ZXBDIST/scratch $ZXBDIST/.git $ZXBDIST/*.spec $ZXBDIST/__pycache__
find $ZXBDIST -type d -name ".*" -exec rm -rf {} \; 2>/dev/null || true
find $ZXBDIST -type d -name ".*" -delete

tar -zcf zxbasic.tar.gz $ZXBDIST
zip -9qr zxbasic.zip $ZXBDIST

mv zxbasic.zip zxbasic-$RELEASE.zip
mv zxbasic.tar.gz zxbasic-$RELEASE.tar.gz

#cd ../$ZXBDIST
#docker run -v "$(pwd):/src/" cdrx/pyinstaller-windows 
#cd ..
#mv $ZXBDIST/dist/windows dist
#cp dist/windows/zxb{asm,pp}/*.exe dist/windows/zxb
#mv dist/zxbasic/{parsetab,library*,examples} dist/windows/zxb
#rm -rf dist/zxbasic
#mv dist/windows/zxb dist/windows/zxbasic

#pushd dist/windows
#zip -9qr zxbasic-$RELEASE-win32.zip zxbasic
#popd
#mv -f dist/windows/zxbasic-$RELEASE-win32.zip dist
#rm -rf dist/windows

cd ..
cp -af win32/* dist/zxbasic
cd dist
zip -9qr zxbasic-$RELEASE-win32.zip zxbasic
rm -rf zxbasic

echo Uploading...
scp zxbasic-$RELEASE{-win32.zip,.tar.gz,.zip} boriel@boriel.com:/var/www/boriel.com/web/files/zxb
echo Done!
echo Download from:
for i in zxbasic-$RELEASE{-win32.zip,.tar.gz,.zip}; do
    echo http://boriel.com/files/zxb/$i
done

